//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.269
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MASGAU.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MASGAU.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        public static System.Drawing.Icon _0001 {
            get {
                object obj = ResourceManager.GetObject("_0001", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        public static System.Drawing.Icon _0002 {
            get {
                object obj = ResourceManager.GetObject("_0002", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        public static System.Drawing.Icon _0003 {
            get {
                object obj = ResourceManager.GetObject("_0003", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        public static System.Drawing.Icon _0004 {
            get {
                object obj = ResourceManager.GetObject("_0004", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        public static System.Drawing.Icon _0005 {
            get {
                object obj = ResourceManager.GetObject("_0005", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        public static System.Drawing.Icon _0006 {
            get {
                object obj = ResourceManager.GetObject("_0006", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        public static System.Drawing.Icon _0007 {
            get {
                object obj = ResourceManager.GetObject("_0007", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        public static System.Drawing.Icon _0008 {
            get {
                object obj = ResourceManager.GetObject("_0008", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        public static System.Drawing.Icon _0009 {
            get {
                object obj = ResourceManager.GetObject("_0009", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        public static System.Drawing.Icon _0010 {
            get {
                object obj = ResourceManager.GetObject("_0010", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        public static System.Drawing.Icon _0011 {
            get {
                object obj = ResourceManager.GetObject("_0011", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        public static System.Drawing.Icon _0012 {
            get {
                object obj = ResourceManager.GetObject("_0012", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        public static System.Drawing.Icon _0013 {
            get {
                object obj = ResourceManager.GetObject("_0013", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        public static System.Drawing.Icon _0014 {
            get {
                object obj = ResourceManager.GetObject("_0014", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        public static System.Drawing.Icon _0015 {
            get {
                object obj = ResourceManager.GetObject("_0015", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        public static System.Drawing.Icon _0016 {
            get {
                object obj = ResourceManager.GetObject("_0016", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        public static System.Drawing.Icon _0017 {
            get {
                object obj = ResourceManager.GetObject("_0017", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        public static System.Drawing.Icon _0018 {
            get {
                object obj = ResourceManager.GetObject("_0018", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        public static System.Drawing.Icon _0019 {
            get {
                object obj = ResourceManager.GetObject("_0019", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        public static System.Drawing.Icon _0020 {
            get {
                object obj = ResourceManager.GetObject("_0020", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        public static System.Drawing.Icon _0021 {
            get {
                object obj = ResourceManager.GetObject("_0021", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        public static System.Drawing.Icon _0022 {
            get {
                object obj = ResourceManager.GetObject("_0022", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        public static System.Drawing.Icon _0023 {
            get {
                object obj = ResourceManager.GetObject("_0023", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        public static System.Drawing.Icon _0024 {
            get {
                object obj = ResourceManager.GetObject("_0024", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        public static System.Drawing.Icon _0025 {
            get {
                object obj = ResourceManager.GetObject("_0025", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        public static System.Drawing.Icon _0026 {
            get {
                object obj = ResourceManager.GetObject("_0026", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        public static System.Drawing.Icon _0027 {
            get {
                object obj = ResourceManager.GetObject("_0027", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        public static System.Drawing.Icon _0028 {
            get {
                object obj = ResourceManager.GetObject("_0028", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        public static System.Drawing.Icon _0029 {
            get {
                object obj = ResourceManager.GetObject("_0029", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        public static System.Drawing.Icon _0030 {
            get {
                object obj = ResourceManager.GetObject("_0030", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        public static System.Drawing.Icon _0031 {
            get {
                object obj = ResourceManager.GetObject("_0031", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        public static System.Drawing.Icon _0032 {
            get {
                object obj = ResourceManager.GetObject("_0032", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        public static System.Drawing.Icon _0033 {
            get {
                object obj = ResourceManager.GetObject("_0033", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        public static System.Drawing.Icon _0034 {
            get {
                object obj = ResourceManager.GetObject("_0034", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        public static System.Drawing.Icon _0035 {
            get {
                object obj = ResourceManager.GetObject("_0035", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        public static System.Drawing.Icon _0036 {
            get {
                object obj = ResourceManager.GetObject("_0036", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        public static System.Drawing.Icon _0037 {
            get {
                object obj = ResourceManager.GetObject("_0037", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        public static System.Drawing.Icon _0038 {
            get {
                object obj = ResourceManager.GetObject("_0038", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        public static System.Drawing.Icon _0039 {
            get {
                object obj = ResourceManager.GetObject("_0039", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        public static System.Drawing.Icon _0040 {
            get {
                object obj = ResourceManager.GetObject("_0040", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        public static System.Drawing.Icon _0041 {
            get {
                object obj = ResourceManager.GetObject("_0041", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        public static System.Drawing.Icon _0042 {
            get {
                object obj = ResourceManager.GetObject("_0042", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        public static System.Drawing.Icon _0043 {
            get {
                object obj = ResourceManager.GetObject("_0043", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        public static System.Drawing.Icon _0044 {
            get {
                object obj = ResourceManager.GetObject("_0044", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        public static System.Drawing.Icon _0045 {
            get {
                object obj = ResourceManager.GetObject("_0045", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        public static System.Drawing.Icon _0046 {
            get {
                object obj = ResourceManager.GetObject("_0046", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        public static System.Drawing.Icon _0047 {
            get {
                object obj = ResourceManager.GetObject("_0047", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        public static System.Drawing.Icon _0048 {
            get {
                object obj = ResourceManager.GetObject("_0048", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        public static System.Drawing.Icon _0049 {
            get {
                object obj = ResourceManager.GetObject("_0049", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        public static System.Drawing.Icon _0050 {
            get {
                object obj = ResourceManager.GetObject("_0050", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        public static System.Drawing.Icon _0051 {
            get {
                object obj = ResourceManager.GetObject("_0051", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        public static System.Drawing.Icon _0052 {
            get {
                object obj = ResourceManager.GetObject("_0052", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        public static System.Drawing.Icon _0053 {
            get {
                object obj = ResourceManager.GetObject("_0053", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        public static System.Drawing.Icon _0054 {
            get {
                object obj = ResourceManager.GetObject("_0054", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        public static System.Drawing.Icon _0055 {
            get {
                object obj = ResourceManager.GetObject("_0055", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        public static System.Drawing.Icon _0056 {
            get {
                object obj = ResourceManager.GetObject("_0056", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        public static System.Drawing.Icon _0057 {
            get {
                object obj = ResourceManager.GetObject("_0057", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        public static System.Drawing.Icon _0058 {
            get {
                object obj = ResourceManager.GetObject("_0058", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        public static System.Drawing.Icon _0059 {
            get {
                object obj = ResourceManager.GetObject("_0059", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        public static System.Drawing.Icon _0060 {
            get {
                object obj = ResourceManager.GetObject("_0060", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        public static System.Drawing.Icon MASGAUIcon {
            get {
                object obj = ResourceManager.GetObject("MASGAUIcon", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
    }
}
