
// This file has been generated by the GUI designer. Do not modify.

public partial class MainWindow
{
	private global::Gtk.UIManager UIManager;
	private global::Gtk.Action refreshAction;
	private global::Gtk.RadioAction Action;
	private global::Gtk.Action GamesAction;
	private global::Gtk.Action BackupAction;
	private global::Gtk.Action RestoreAction;
	private global::Gtk.Action ToolsAction;
	private global::Gtk.Action SettingsAction;
	private global::Gtk.Action HelpAction;
	private global::Gtk.Action refreshAction1;
	private global::Gtk.VBox vbox1;
	private global::Gtk.MenuBar menubar3;
	private global::Gtk.Toolbar toolbar2;
	private global::Gtk.HPaned hpaned4;
	private global::Gtk.ScrolledWindow GtkScrolledWindow;
	private global::Gtk.NodeView gamesNodes;
	private global::Gtk.HBox hbox4;
	private global::Gtk.ScrolledWindow GtkScrolledWindow1;
	private global::Gtk.NodeView archivesNodes;
	private global::Gtk.Label label3;
	private global::Gtk.HBox hbox1;
	private global::Gtk.Button button1;
	private global::Gtk.Statusbar statusbar4;
	private global::Gtk.ProgressBar progressbar1;
	private global::Gtk.Label label2;
	private global::Gtk.Button button3;
	
	protected virtual void Build ()
	{
		global::Stetic.Gui.Initialize (this);
		// Widget MainWindow
		this.UIManager = new global::Gtk.UIManager ();
		global::Gtk.ActionGroup w1 = new global::Gtk.ActionGroup ("Default");
		this.refreshAction = new global::Gtk.Action ("refreshAction", null, null, "gtk-refresh");
		w1.Add (this.refreshAction, null);
		this.Action = new global::Gtk.RadioAction ("Action", null, null, null, 0);
		this.Action.Group = new global::GLib.SList (global::System.IntPtr.Zero);
		w1.Add (this.Action, null);
		this.GamesAction = new global::Gtk.Action ("GamesAction", global::Mono.Unix.Catalog.GetString ("Games"), null, null);
		this.GamesAction.ShortLabel = global::Mono.Unix.Catalog.GetString ("Games");
		w1.Add (this.GamesAction, null);
		this.BackupAction = new global::Gtk.Action ("BackupAction", global::Mono.Unix.Catalog.GetString ("Backup"), null, null);
		this.BackupAction.ShortLabel = global::Mono.Unix.Catalog.GetString ("Backup");
		w1.Add (this.BackupAction, null);
		this.RestoreAction = new global::Gtk.Action ("RestoreAction", global::Mono.Unix.Catalog.GetString ("Restore"), null, null);
		this.RestoreAction.ShortLabel = global::Mono.Unix.Catalog.GetString ("Restore");
		w1.Add (this.RestoreAction, null);
		this.ToolsAction = new global::Gtk.Action ("ToolsAction", global::Mono.Unix.Catalog.GetString ("Tools"), null, null);
		this.ToolsAction.ShortLabel = global::Mono.Unix.Catalog.GetString ("Tools");
		w1.Add (this.ToolsAction, null);
		this.SettingsAction = new global::Gtk.Action ("SettingsAction", global::Mono.Unix.Catalog.GetString ("Settings"), null, null);
		this.SettingsAction.ShortLabel = global::Mono.Unix.Catalog.GetString ("Settings");
		w1.Add (this.SettingsAction, null);
		this.HelpAction = new global::Gtk.Action ("HelpAction", global::Mono.Unix.Catalog.GetString ("Help"), null, null);
		this.HelpAction.ShortLabel = global::Mono.Unix.Catalog.GetString ("Help");
		w1.Add (this.HelpAction, null);
		this.refreshAction1 = new global::Gtk.Action ("refreshAction1", null, null, "gtk-refresh");
		w1.Add (this.refreshAction1, null);
		this.UIManager.InsertActionGroup (w1, 0);
		this.AddAccelGroup (this.UIManager.AccelGroup);
		this.Name = "MainWindow";
		this.Title = global::Mono.Unix.Catalog.GetString ("MASGAU");
		this.Icon = global::Gdk.Pixbuf.LoadFromResource ("MASGAU.GTK.masgau.ico");
		this.WindowPosition = ((global::Gtk.WindowPosition)(4));
		// Container child MainWindow.Gtk.Container+ContainerChild
		this.vbox1 = new global::Gtk.VBox ();
		this.vbox1.Name = "vbox1";
		// Container child vbox1.Gtk.Box+BoxChild
		this.UIManager.AddUiFromString (@"<ui><menubar name='menubar3'><menu name='GamesAction' action='GamesAction'/><menu name='BackupAction' action='BackupAction'/><menu name='RestoreAction' action='RestoreAction'/><menu name='ToolsAction' action='ToolsAction'/><menu name='SettingsAction' action='SettingsAction'/><menu name='HelpAction' action='HelpAction'/></menubar></ui>");
		this.menubar3 = ((global::Gtk.MenuBar)(this.UIManager.GetWidget ("/menubar3")));
		this.menubar3.Name = "menubar3";
		this.vbox1.Add (this.menubar3);
		global::Gtk.Box.BoxChild w2 = ((global::Gtk.Box.BoxChild)(this.vbox1 [this.menubar3]));
		w2.Position = 0;
		w2.Expand = false;
		w2.Fill = false;
		// Container child vbox1.Gtk.Box+BoxChild
		this.UIManager.AddUiFromString ("<ui><toolbar name=\'toolbar2\'><toolitem name=\'refreshAction1\' action=\'refreshActio" +
			"n1\'/></toolbar></ui>");
		this.toolbar2 = ((global::Gtk.Toolbar)(this.UIManager.GetWidget ("/toolbar2")));
		this.toolbar2.Name = "toolbar2";
		this.toolbar2.ShowArrow = false;
		this.vbox1.Add (this.toolbar2);
		global::Gtk.Box.BoxChild w3 = ((global::Gtk.Box.BoxChild)(this.vbox1 [this.toolbar2]));
		w3.Position = 1;
		w3.Expand = false;
		w3.Fill = false;
		// Container child vbox1.Gtk.Box+BoxChild
		this.hpaned4 = new global::Gtk.HPaned ();
		this.hpaned4.CanFocus = true;
		this.hpaned4.Name = "hpaned4";
		this.hpaned4.Position = 511;
		// Container child hpaned4.Gtk.Paned+PanedChild
		this.GtkScrolledWindow = new global::Gtk.ScrolledWindow ();
		this.GtkScrolledWindow.Name = "GtkScrolledWindow";
		this.GtkScrolledWindow.ShadowType = ((global::Gtk.ShadowType)(1));
		// Container child GtkScrolledWindow.Gtk.Container+ContainerChild
		this.gamesNodes = new global::Gtk.NodeView ();
		this.gamesNodes.CanFocus = true;
		this.gamesNodes.Name = "gamesNodes";
		this.GtkScrolledWindow.Add (this.gamesNodes);
		this.hpaned4.Add (this.GtkScrolledWindow);
		global::Gtk.Paned.PanedChild w5 = ((global::Gtk.Paned.PanedChild)(this.hpaned4 [this.GtkScrolledWindow]));
		w5.Resize = false;
		// Container child hpaned4.Gtk.Paned+PanedChild
		this.hbox4 = new global::Gtk.HBox ();
		this.hbox4.Name = "hbox4";
		this.hbox4.Spacing = 6;
		// Container child hbox4.Gtk.Box+BoxChild
		this.GtkScrolledWindow1 = new global::Gtk.ScrolledWindow ();
		this.GtkScrolledWindow1.Name = "GtkScrolledWindow1";
		this.GtkScrolledWindow1.ShadowType = ((global::Gtk.ShadowType)(1));
		// Container child GtkScrolledWindow1.Gtk.Container+ContainerChild
		this.archivesNodes = new global::Gtk.NodeView ();
		this.archivesNodes.CanFocus = true;
		this.archivesNodes.Name = "archivesNodes";
		this.GtkScrolledWindow1.Add (this.archivesNodes);
		this.hbox4.Add (this.GtkScrolledWindow1);
		global::Gtk.Box.BoxChild w7 = ((global::Gtk.Box.BoxChild)(this.hbox4 [this.GtkScrolledWindow1]));
		w7.Position = 0;
		// Container child hbox4.Gtk.Box+BoxChild
		this.label3 = new global::Gtk.Label ();
		this.label3.Name = "label3";
		this.label3.LabelProp = global::Mono.Unix.Catalog.GetString ("label3");
		this.label3.Angle = 270D;
		this.hbox4.Add (this.label3);
		global::Gtk.Box.BoxChild w8 = ((global::Gtk.Box.BoxChild)(this.hbox4 [this.label3]));
		w8.Position = 1;
		w8.Expand = false;
		w8.Fill = false;
		this.hpaned4.Add (this.hbox4);
		this.vbox1.Add (this.hpaned4);
		global::Gtk.Box.BoxChild w10 = ((global::Gtk.Box.BoxChild)(this.vbox1 [this.hpaned4]));
		w10.Position = 2;
		// Container child vbox1.Gtk.Box+BoxChild
		this.hbox1 = new global::Gtk.HBox ();
		this.hbox1.Name = "hbox1";
		this.hbox1.Spacing = 6;
		// Container child hbox1.Gtk.Box+BoxChild
		this.button1 = new global::Gtk.Button ();
		this.button1.CanFocus = true;
		this.button1.Name = "button1";
		this.button1.UseUnderline = true;
		this.button1.Label = global::Mono.Unix.Catalog.GetString ("GtkButton");
		this.hbox1.Add (this.button1);
		global::Gtk.Box.BoxChild w11 = ((global::Gtk.Box.BoxChild)(this.hbox1 [this.button1]));
		w11.Position = 0;
		w11.Expand = false;
		w11.Fill = false;
		// Container child hbox1.Gtk.Box+BoxChild
		this.statusbar4 = new global::Gtk.Statusbar ();
		this.statusbar4.Name = "statusbar4";
		this.statusbar4.Spacing = 6;
		// Container child statusbar4.Gtk.Box+BoxChild
		this.progressbar1 = new global::Gtk.ProgressBar ();
		this.progressbar1.Name = "progressbar1";
		this.statusbar4.Add (this.progressbar1);
		global::Gtk.Box.BoxChild w12 = ((global::Gtk.Box.BoxChild)(this.statusbar4 [this.progressbar1]));
		w12.Position = 1;
		// Container child statusbar4.Gtk.Box+BoxChild
		this.label2 = new global::Gtk.Label ();
		this.label2.Name = "label2";
		this.label2.LabelProp = global::Mono.Unix.Catalog.GetString ("label2");
		this.statusbar4.Add (this.label2);
		global::Gtk.Box.BoxChild w13 = ((global::Gtk.Box.BoxChild)(this.statusbar4 [this.label2]));
		w13.Position = 2;
		w13.Expand = false;
		w13.Fill = false;
		// Container child statusbar4.Gtk.Box+BoxChild
		this.button3 = new global::Gtk.Button ();
		this.button3.CanFocus = true;
		this.button3.Name = "button3";
		this.button3.UseUnderline = true;
		this.button3.Label = global::Mono.Unix.Catalog.GetString ("GtkButton");
		this.statusbar4.Add (this.button3);
		global::Gtk.Box.BoxChild w14 = ((global::Gtk.Box.BoxChild)(this.statusbar4 [this.button3]));
		w14.Position = 3;
		w14.Expand = false;
		w14.Fill = false;
		this.hbox1.Add (this.statusbar4);
		global::Gtk.Box.BoxChild w15 = ((global::Gtk.Box.BoxChild)(this.hbox1 [this.statusbar4]));
		w15.Position = 1;
		this.vbox1.Add (this.hbox1);
		global::Gtk.Box.BoxChild w16 = ((global::Gtk.Box.BoxChild)(this.vbox1 [this.hbox1]));
		w16.Position = 3;
		w16.Expand = false;
		w16.Fill = false;
		this.Add (this.vbox1);
		if ((this.Child != null)) {
			this.Child.ShowAll ();
		}
		this.DefaultWidth = 781;
		this.DefaultHeight = 494;
		this.Show ();
		this.DeleteEvent += new global::Gtk.DeleteEventHandler (this.OnDeleteEvent);
		this.Mapped += new global::System.EventHandler (this.OnMapped);
		this.Realized += new global::System.EventHandler (this.OnRealized);
	}
}
