
// This file has been generated by the GUI designer. Do not modify.
namespace MASGAU.Gtk
{
	public partial class SettingsWidget
	{
		protected virtual void Build ()
		{
			global::Stetic.Gui.Initialize (this);
			// Widget MASGAU.Gtk.SettingsWidget
			global::Stetic.BinContainer.Attach (this);
			this.Name = "MASGAU.Gtk.SettingsWidget";
			if ((this.Child != null)) {
				this.Child.ShowAll ();
			}
			this.Hide ();
		}
	}
}
