
// This file has been generated by the GUI designer. Do not modify.
namespace MASGAU
{
	public partial class Entry
	{
		private global::Gtk.Entry entry1;
		
		protected virtual void Build ()
		{
			global::Stetic.Gui.Initialize (this);
			// Widget MASGAU.Entry
			global::Stetic.BinContainer.Attach (this);
			this.Name = "MASGAU.Entry";
			// Container child MASGAU.Entry.Gtk.Container+ContainerChild
			this.entry1 = new global::Gtk.Entry ();
			this.entry1.CanFocus = true;
			this.entry1.Name = "entry1";
			this.entry1.IsEditable = true;
			this.entry1.InvisibleChar = '●';
			this.Add (this.entry1);
			if ((this.Child != null)) {
				this.Child.ShowAll ();
			}
			this.Hide ();
		}
	}
}
