
// This file has been generated by the GUI designer. Do not modify.
namespace MASGAU
{
	public partial class SettingsWidget
	{
		protected virtual void Build ()
		{
			global::Stetic.Gui.Initialize (this);
			// Widget MASGAU.SettingsWidget
			global::Stetic.BinContainer.Attach (this);
			this.Name = "MASGAU.SettingsWidget";
			if ((this.Child != null)) {
				this.Child.ShowAll ();
			}
			this.Hide ();
		}
	}
}
