
// This file has been generated by the GUI designer. Do not modify.
namespace MASGAU.Gtk
{
	public partial class WrappedButton
	{
		private global::Gtk.Button button29;
		
		protected virtual void Build ()
		{
			global::Stetic.Gui.Initialize (this);
			// Widget MASGAU.Gtk.WrappedButton
			global::Stetic.BinContainer.Attach (this);
			this.Name = "MASGAU.Gtk.WrappedButton";
			// Container child MASGAU.Gtk.WrappedButton.Gtk.Container+ContainerChild
			this.button29 = new global::Gtk.Button ();
			this.button29.CanFocus = true;
			this.button29.Name = "button29";
			this.button29.UseUnderline = true;
			this.button29.Label = global::Mono.Unix.Catalog.GetString ("GtkButton");
			this.Add (this.button29);
			if ((this.Child != null)) {
				this.Child.ShowAll ();
			}
			this.Hide ();
		}
	}
}
