
// This file has been generated by the GUI designer. Do not modify.
namespace MASGAU.Gtk
{
	public partial class WrappedEntry
	{
		private global::Gtk.Entry entry1;
		
		protected virtual void Build ()
		{
			global::Stetic.Gui.Initialize (this);
			// Widget MASGAU.Gtk.WrappedEntry
			global::Stetic.BinContainer.Attach (this);
			this.Name = "MASGAU.Gtk.WrappedEntry";
			// Container child MASGAU.Gtk.WrappedEntry.Gtk.Container+ContainerChild
			this.entry1 = new global::Gtk.Entry ();
			this.entry1.CanFocus = true;
			this.entry1.Name = "entry1";
			this.entry1.IsEditable = true;
			this.entry1.InvisibleChar = '●';
			this.Add (this.entry1);
			if ((this.Child != null)) {
				this.Child.ShowAll ();
			}
			this.Hide ();
			this.entry1.Changed += new global::System.EventHandler (this.HandleEntry1Changed);
		}
	}
}
