
// This file has been generated by the GUI designer. Do not modify.
namespace MASGAU
{
	public partial class SubmitButton
	{
		private global::Gtk.HButtonBox hbuttonbox2;
		private global::Gtk.Button submitButton;
		private global::Gtk.Button closeButton;
		private global::Gtk.Button cancelButton;
		
		protected virtual void Build ()
		{
			global::Stetic.Gui.Initialize (this);
			// Widget MASGAU.SubmitButton
			global::Stetic.BinContainer.Attach (this);
			this.Name = "MASGAU.SubmitButton";
			// Container child MASGAU.SubmitButton.Gtk.Container+ContainerChild
			this.hbuttonbox2 = new global::Gtk.HButtonBox ();
			this.hbuttonbox2.Name = "hbuttonbox2";
			// Container child hbuttonbox2.Gtk.ButtonBox+ButtonBoxChild
			this.submitButton = new global::Gtk.Button ();
			this.submitButton.CanFocus = true;
			this.submitButton.Name = "submitButton";
			this.submitButton.UseUnderline = true;
			// Container child submitButton.Gtk.Container+ContainerChild
			global::Gtk.Alignment w1 = new global::Gtk.Alignment (0.5F, 0.5F, 0F, 0F);
			// Container child GtkAlignment.Gtk.Container+ContainerChild
			global::Gtk.HBox w2 = new global::Gtk.HBox ();
			w2.Spacing = 2;
			// Container child GtkHBox.Gtk.Container+ContainerChild
			global::Gtk.Image w3 = new global::Gtk.Image ();
			w3.Pixbuf = global::Stetic.IconLoader.LoadIcon (this, "gtk-go-up", global::Gtk.IconSize.Menu);
			w2.Add (w3);
			// Container child GtkHBox.Gtk.Container+ContainerChild
			global::Gtk.Label w5 = new global::Gtk.Label ();
			w5.LabelProp = global::Mono.Unix.Catalog.GetString ("SubmitButton");
			w5.UseUnderline = true;
			w2.Add (w5);
			w1.Add (w2);
			this.submitButton.Add (w1);
			this.hbuttonbox2.Add (this.submitButton);
			global::Gtk.ButtonBox.ButtonBoxChild w9 = ((global::Gtk.ButtonBox.ButtonBoxChild)(this.hbuttonbox2 [this.submitButton]));
			w9.Expand = false;
			w9.Fill = false;
			// Container child hbuttonbox2.Gtk.ButtonBox+ButtonBoxChild
			this.closeButton = new global::Gtk.Button ();
			this.closeButton.CanFocus = true;
			this.closeButton.Name = "closeButton";
			this.closeButton.UseUnderline = true;
			// Container child closeButton.Gtk.Container+ContainerChild
			global::Gtk.Alignment w10 = new global::Gtk.Alignment (0.5F, 0.5F, 0F, 0F);
			// Container child GtkAlignment.Gtk.Container+ContainerChild
			global::Gtk.HBox w11 = new global::Gtk.HBox ();
			w11.Spacing = 2;
			// Container child GtkHBox.Gtk.Container+ContainerChild
			global::Gtk.Image w12 = new global::Gtk.Image ();
			w12.Pixbuf = global::Stetic.IconLoader.LoadIcon (this, "gtk-close", global::Gtk.IconSize.Menu);
			w11.Add (w12);
			// Container child GtkHBox.Gtk.Container+ContainerChild
			global::Gtk.Label w14 = new global::Gtk.Label ();
			w14.LabelProp = global::Mono.Unix.Catalog.GetString ("CloseButton");
			w14.UseUnderline = true;
			w11.Add (w14);
			w10.Add (w11);
			this.closeButton.Add (w10);
			this.hbuttonbox2.Add (this.closeButton);
			global::Gtk.ButtonBox.ButtonBoxChild w18 = ((global::Gtk.ButtonBox.ButtonBoxChild)(this.hbuttonbox2 [this.closeButton]));
			w18.Position = 1;
			w18.Expand = false;
			w18.Fill = false;
			// Container child hbuttonbox2.Gtk.ButtonBox+ButtonBoxChild
			this.cancelButton = new global::Gtk.Button ();
			this.cancelButton.CanFocus = true;
			this.cancelButton.Name = "cancelButton";
			this.cancelButton.UseUnderline = true;
			// Container child cancelButton.Gtk.Container+ContainerChild
			global::Gtk.Alignment w19 = new global::Gtk.Alignment (0.5F, 0.5F, 0F, 0F);
			// Container child GtkAlignment.Gtk.Container+ContainerChild
			global::Gtk.HBox w20 = new global::Gtk.HBox ();
			w20.Spacing = 2;
			// Container child GtkHBox.Gtk.Container+ContainerChild
			global::Gtk.Image w21 = new global::Gtk.Image ();
			w21.Pixbuf = global::Stetic.IconLoader.LoadIcon (this, "gtk-cancel", global::Gtk.IconSize.Menu);
			w20.Add (w21);
			// Container child GtkHBox.Gtk.Container+ContainerChild
			global::Gtk.Label w23 = new global::Gtk.Label ();
			w23.LabelProp = global::Mono.Unix.Catalog.GetString ("CancelButton");
			w23.UseUnderline = true;
			w20.Add (w23);
			w19.Add (w20);
			this.cancelButton.Add (w19);
			this.hbuttonbox2.Add (this.cancelButton);
			global::Gtk.ButtonBox.ButtonBoxChild w27 = ((global::Gtk.ButtonBox.ButtonBoxChild)(this.hbuttonbox2 [this.cancelButton]));
			w27.Position = 2;
			w27.Expand = false;
			w27.Fill = false;
			this.Add (this.hbuttonbox2);
			if ((this.Child != null)) {
				this.Child.ShowAll ();
			}
			this.Hide ();
			this.closeButton.Clicked += new global::System.EventHandler (this.OnCloseButtonClicked);
		}
	}
}
