
// This file has been generated by the GUI designer. Do not modify.
namespace MASGAU
{
	public partial class EmailDialog
	{
		private global::Gtk.Frame frame1;
		private global::Gtk.Alignment GtkAlignment2;
		private global::Gtk.Entry emailTxt;
		private global::Gtk.Label emailLabel;
		private global::Gtk.Button buttonCancel;
		private global::Gtk.Button buttonSave;
		
		protected virtual void Build ()
		{
			global::Stetic.Gui.Initialize (this);
			// Widget MASGAU.EmailDialog
			this.Name = "MASGAU.EmailDialog";
			this.Title = global::Mono.Unix.Catalog.GetString ("EmailRequest");
			this.WindowPosition = ((global::Gtk.WindowPosition)(4));
			// Internal child MASGAU.EmailDialog.VBox
			global::Gtk.VBox w1 = this.VBox;
			w1.Name = "dialog1_VBox";
			w1.BorderWidth = ((uint)(2));
			// Container child dialog1_VBox.Gtk.Box+BoxChild
			this.frame1 = new global::Gtk.Frame ();
			this.frame1.Name = "frame1";
			this.frame1.ShadowType = ((global::Gtk.ShadowType)(0));
			// Container child frame1.Gtk.Container+ContainerChild
			this.GtkAlignment2 = new global::Gtk.Alignment (0F, 0F, 1F, 1F);
			this.GtkAlignment2.Name = "GtkAlignment2";
			this.GtkAlignment2.LeftPadding = ((uint)(12));
			// Container child GtkAlignment2.Gtk.Container+ContainerChild
			this.emailTxt = new global::Gtk.Entry ();
			this.emailTxt.CanFocus = true;
			this.emailTxt.Name = "emailTxt";
			this.emailTxt.IsEditable = true;
			this.emailTxt.InvisibleChar = '●';
			this.GtkAlignment2.Add (this.emailTxt);
			this.frame1.Add (this.GtkAlignment2);
			this.emailLabel = new global::Gtk.Label ();
			this.emailLabel.Name = "emailLabel";
			this.emailLabel.LabelProp = global::Mono.Unix.Catalog.GetString ("ChangeLaterInSettings");
			this.emailLabel.UseMarkup = true;
			this.frame1.LabelWidget = this.emailLabel;
			w1.Add (this.frame1);
			global::Gtk.Box.BoxChild w4 = ((global::Gtk.Box.BoxChild)(w1 [this.frame1]));
			w4.Position = 0;
			w4.Expand = false;
			w4.Fill = false;
			// Internal child MASGAU.EmailDialog.ActionArea
			global::Gtk.HButtonBox w5 = this.ActionArea;
			w5.Name = "dialog1_ActionArea";
			w5.Spacing = 10;
			w5.BorderWidth = ((uint)(5));
			w5.LayoutStyle = ((global::Gtk.ButtonBoxStyle)(4));
			// Container child dialog1_ActionArea.Gtk.ButtonBox+ButtonBoxChild
			this.buttonCancel = new global::Gtk.Button ();
			this.buttonCancel.CanDefault = true;
			this.buttonCancel.CanFocus = true;
			this.buttonCancel.Name = "buttonCancel";
			this.buttonCancel.UseStock = true;
			this.buttonCancel.UseUnderline = true;
			this.buttonCancel.Label = "gtk-cancel";
			this.AddActionWidget (this.buttonCancel, -6);
			global::Gtk.ButtonBox.ButtonBoxChild w6 = ((global::Gtk.ButtonBox.ButtonBoxChild)(w5 [this.buttonCancel]));
			w6.Expand = false;
			w6.Fill = false;
			// Container child dialog1_ActionArea.Gtk.ButtonBox+ButtonBoxChild
			this.buttonSave = new global::Gtk.Button ();
			this.buttonSave.Sensitive = false;
			this.buttonSave.CanDefault = true;
			this.buttonSave.CanFocus = true;
			this.buttonSave.Name = "buttonSave";
			this.buttonSave.UseStock = true;
			this.buttonSave.UseUnderline = true;
			this.buttonSave.Label = "gtk-save";
			this.AddActionWidget (this.buttonSave, 0);
			global::Gtk.ButtonBox.ButtonBoxChild w7 = ((global::Gtk.ButtonBox.ButtonBoxChild)(w5 [this.buttonSave]));
			w7.Position = 1;
			w7.Expand = false;
			w7.Fill = false;
			if ((this.Child != null)) {
				this.Child.ShowAll ();
			}
			this.DefaultWidth = 400;
			this.DefaultHeight = 300;
			this.Show ();
			this.emailTxt.Changed += new global::System.EventHandler (this.OnEmailTxtChanged);
		}
	}
}
