using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.IO;
using System.Xml;
using XmlData;
using GameSaveInfo;
namespace MASGAU {
    public class CustomGameXmlFile: GameXmlFile {
        public CustomGameXmlFile(FileInfo file)
            : base(file) {



        }

        protected override GameSaveInfo.Game CreateDataEntry(System.Xml.XmlElement element) {
            return new CustomGame(element);
        }


        public CustomGame createCustomGame(string title, DirectoryInfo location, string saves, string ignores) {
            CustomGame game = new CustomGame(title, location, saves, ignores, this);
            game.SourceFile = this;
            this.Add(game);
            return game;
        }

        protected override XmlElement CreatRootNode() {
            XmlElement ele = base.CreatRootNode();

            XmlComment comment = this.CreateComment("This file contains custom game entries generated by MASGAU\nDO NOT EDIT THIS FILE\nIF YOU WANT TO ADD NEW ENTRIES YOURSELF USE THE new.xml FILE");
            ele.AppendChild(comment);

            return ele;
        }

    }
}
