
// This file has been generated by the GUI designer. Do not modify.

public partial class AnalyzerWindow
{
	private global::Gtk.VBox vbox1;
	private global::Gtk.Frame frame2;
	private global::Gtk.Alignment GtkAlignment;
	private global::MASGAU.Gtk.WrappedEntry nameEntry;
	private global::Gtk.Label gameNameLbl;
	private global::Gtk.Notebook notebook1;
	private global::Gtk.VBox vbox3;
	private global::Gtk.Frame frame3;
	private global::Gtk.Alignment GtkAlignment1;
	private global::MASGAU.Gtk.WrapperFileChooserButton installLocation;
	private global::Gtk.Label gameLocationLbl;
	private global::Gtk.Frame frame4;
	private global::Gtk.Alignment GtkAlignment2;
	private global::MASGAU.Gtk.WrapperFileChooserButton saveLocation;
	private global::Gtk.Label saveLocationLbl;
	private global::MASGAU.Gtk.WrappedButton scanBtn;
	private global::Gtk.Label linuxLabel;
	private global::Gtk.VBox vbox2;
	private global::Gtk.Frame frame1;
	private global::Gtk.Alignment GtkAlignment4;
	private global::Gtk.HBox hbox1;
	private global::MASGAU.Gtk.WrappedEntry prefixEntry;
	private global::Gtk.Label label4;
	private global::MASGAU.Gtk.WrappedEntry suffixEntry;
	private global::Gtk.Label codeLabel;
	private global::Gtk.Frame frame5;
	private global::Gtk.Alignment GtkAlignment5;
	private global::MASGAU.Gtk.WrapperFileChooserButton psLocation;
	private global::Gtk.Label psLocationLabel;
	private global::MASGAU.Gtk.WrappedButton psScanBtn;
	private global::Gtk.Label psLabel;
	private global::Gtk.VBox vbox6;
	private global::Gtk.Frame frame6;
	private global::Gtk.Alignment GtkAlignment7;
	private global::MASGAU.Gtk.WrappedEntry emailEntry;
	private global::Gtk.Label emailLabel;
	private global::Gtk.Label settingsLabel;
	
	protected virtual void Build ()
	{
		global::Stetic.Gui.Initialize (this);
		// Widget AnalyzerWindow
		this.Name = "AnalyzerWindow";
		this.Title = global::Mono.Unix.Catalog.GetString ("AnalyzerWindowTitle");
		this.WindowPosition = ((global::Gtk.WindowPosition)(4));
		this.Resizable = false;
		this.AllowGrow = false;
		// Container child AnalyzerWindow.Gtk.Container+ContainerChild
		this.vbox1 = new global::Gtk.VBox ();
		this.vbox1.Name = "vbox1";
		this.vbox1.Spacing = 6;
		// Container child vbox1.Gtk.Box+BoxChild
		this.frame2 = new global::Gtk.Frame ();
		this.frame2.Name = "frame2";
		this.frame2.ShadowType = ((global::Gtk.ShadowType)(0));
		// Container child frame2.Gtk.Container+ContainerChild
		this.GtkAlignment = new global::Gtk.Alignment (0F, 0F, 1F, 1F);
		this.GtkAlignment.Name = "GtkAlignment";
		this.GtkAlignment.LeftPadding = ((uint)(12));
		// Container child GtkAlignment.Gtk.Container+ContainerChild
		this.nameEntry = new global::MASGAU.Gtk.WrappedEntry ();
		this.nameEntry.Events = ((global::Gdk.EventMask)(256));
		this.nameEntry.Name = "nameEntry";
		this.GtkAlignment.Add (this.nameEntry);
		this.frame2.Add (this.GtkAlignment);
		this.gameNameLbl = new global::Gtk.Label ();
		this.gameNameLbl.Name = "gameNameLbl";
		this.gameNameLbl.LabelProp = global::Mono.Unix.Catalog.GetString ("GameNameQuestion");
		this.gameNameLbl.UseMarkup = true;
		this.frame2.LabelWidget = this.gameNameLbl;
		this.vbox1.Add (this.frame2);
		global::Gtk.Box.BoxChild w3 = ((global::Gtk.Box.BoxChild)(this.vbox1 [this.frame2]));
		w3.Position = 0;
		w3.Expand = false;
		w3.Fill = false;
		// Container child vbox1.Gtk.Box+BoxChild
		this.notebook1 = new global::Gtk.Notebook ();
		this.notebook1.CanFocus = true;
		this.notebook1.Name = "notebook1";
		this.notebook1.CurrentPage = 0;
		// Container child notebook1.Gtk.Notebook+NotebookChild
		this.vbox3 = new global::Gtk.VBox ();
		this.vbox3.Name = "vbox3";
		this.vbox3.Spacing = 6;
		// Container child vbox3.Gtk.Box+BoxChild
		this.frame3 = new global::Gtk.Frame ();
		this.frame3.Name = "frame3";
		this.frame3.ShadowType = ((global::Gtk.ShadowType)(0));
		// Container child frame3.Gtk.Container+ContainerChild
		this.GtkAlignment1 = new global::Gtk.Alignment (0F, 0F, 1F, 1F);
		this.GtkAlignment1.Name = "GtkAlignment1";
		this.GtkAlignment1.LeftPadding = ((uint)(12));
		// Container child GtkAlignment1.Gtk.Container+ContainerChild
		this.installLocation = new global::MASGAU.Gtk.WrapperFileChooserButton ();
		this.installLocation.Events = ((global::Gdk.EventMask)(256));
		this.installLocation.Name = "installLocation";
		this.GtkAlignment1.Add (this.installLocation);
		this.frame3.Add (this.GtkAlignment1);
		this.gameLocationLbl = new global::Gtk.Label ();
		this.gameLocationLbl.Name = "gameLocationLbl";
		this.gameLocationLbl.LabelProp = global::Mono.Unix.Catalog.GetString ("GameInstallQuestion");
		this.gameLocationLbl.UseMarkup = true;
		this.frame3.LabelWidget = this.gameLocationLbl;
		this.vbox3.Add (this.frame3);
		global::Gtk.Box.BoxChild w6 = ((global::Gtk.Box.BoxChild)(this.vbox3 [this.frame3]));
		w6.Position = 0;
		w6.Expand = false;
		w6.Fill = false;
		// Container child vbox3.Gtk.Box+BoxChild
		this.frame4 = new global::Gtk.Frame ();
		this.frame4.Name = "frame4";
		this.frame4.ShadowType = ((global::Gtk.ShadowType)(0));
		// Container child frame4.Gtk.Container+ContainerChild
		this.GtkAlignment2 = new global::Gtk.Alignment (0F, 0F, 1F, 1F);
		this.GtkAlignment2.Name = "GtkAlignment2";
		this.GtkAlignment2.LeftPadding = ((uint)(12));
		// Container child GtkAlignment2.Gtk.Container+ContainerChild
		this.saveLocation = new global::MASGAU.Gtk.WrapperFileChooserButton ();
		this.saveLocation.Events = ((global::Gdk.EventMask)(256));
		this.saveLocation.Name = "saveLocation";
		this.GtkAlignment2.Add (this.saveLocation);
		this.frame4.Add (this.GtkAlignment2);
		this.saveLocationLbl = new global::Gtk.Label ();
		this.saveLocationLbl.Name = "saveLocationLbl";
		this.saveLocationLbl.LabelProp = global::Mono.Unix.Catalog.GetString ("GameSavesQuestion");
		this.saveLocationLbl.UseMarkup = true;
		this.frame4.LabelWidget = this.saveLocationLbl;
		this.vbox3.Add (this.frame4);
		global::Gtk.Box.BoxChild w9 = ((global::Gtk.Box.BoxChild)(this.vbox3 [this.frame4]));
		w9.Position = 1;
		w9.Expand = false;
		w9.Fill = false;
		// Container child vbox3.Gtk.Box+BoxChild
		this.scanBtn = new global::MASGAU.Gtk.WrappedButton ();
		this.scanBtn.Events = ((global::Gdk.EventMask)(256));
		this.scanBtn.Name = "scanBtn";
		this.scanBtn.Label = "ScanButton";
		this.vbox3.Add (this.scanBtn);
		global::Gtk.Box.BoxChild w10 = ((global::Gtk.Box.BoxChild)(this.vbox3 [this.scanBtn]));
		w10.Position = 2;
		w10.Expand = false;
		w10.Fill = false;
		this.notebook1.Add (this.vbox3);
		// Notebook tab
		this.linuxLabel = new global::Gtk.Label ();
		this.linuxLabel.Name = "linuxLabel";
		this.linuxLabel.LabelProp = global::Mono.Unix.Catalog.GetString ("Linux");
		this.notebook1.SetTabLabel (this.vbox3, this.linuxLabel);
		this.linuxLabel.ShowAll ();
		// Container child notebook1.Gtk.Notebook+NotebookChild
		this.vbox2 = new global::Gtk.VBox ();
		this.vbox2.Name = "vbox2";
		this.vbox2.Spacing = 6;
		// Container child vbox2.Gtk.Box+BoxChild
		this.frame1 = new global::Gtk.Frame ();
		this.frame1.Name = "frame1";
		this.frame1.ShadowType = ((global::Gtk.ShadowType)(0));
		// Container child frame1.Gtk.Container+ContainerChild
		this.GtkAlignment4 = new global::Gtk.Alignment (0F, 0F, 1F, 1F);
		this.GtkAlignment4.Name = "GtkAlignment4";
		this.GtkAlignment4.LeftPadding = ((uint)(12));
		// Container child GtkAlignment4.Gtk.Container+ContainerChild
		this.hbox1 = new global::Gtk.HBox ();
		this.hbox1.Name = "hbox1";
		this.hbox1.Spacing = 6;
		// Container child hbox1.Gtk.Box+BoxChild
		this.prefixEntry = new global::MASGAU.Gtk.WrappedEntry ();
		this.prefixEntry.Events = ((global::Gdk.EventMask)(256));
		this.prefixEntry.Name = "prefixEntry";
		this.hbox1.Add (this.prefixEntry);
		global::Gtk.Box.BoxChild w12 = ((global::Gtk.Box.BoxChild)(this.hbox1 [this.prefixEntry]));
		w12.Position = 0;
		// Container child hbox1.Gtk.Box+BoxChild
		this.label4 = new global::Gtk.Label ();
		this.label4.Name = "label4";
		this.label4.LabelProp = global::Mono.Unix.Catalog.GetString ("-");
		this.hbox1.Add (this.label4);
		global::Gtk.Box.BoxChild w13 = ((global::Gtk.Box.BoxChild)(this.hbox1 [this.label4]));
		w13.Position = 1;
		w13.Expand = false;
		w13.Fill = false;
		// Container child hbox1.Gtk.Box+BoxChild
		this.suffixEntry = new global::MASGAU.Gtk.WrappedEntry ();
		this.suffixEntry.Events = ((global::Gdk.EventMask)(256));
		this.suffixEntry.Name = "suffixEntry";
		this.hbox1.Add (this.suffixEntry);
		global::Gtk.Box.BoxChild w14 = ((global::Gtk.Box.BoxChild)(this.hbox1 [this.suffixEntry]));
		w14.Position = 2;
		this.GtkAlignment4.Add (this.hbox1);
		this.frame1.Add (this.GtkAlignment4);
		this.codeLabel = new global::Gtk.Label ();
		this.codeLabel.Name = "codeLabel";
		this.codeLabel.LabelProp = global::Mono.Unix.Catalog.GetString ("PlayStationCodeQuestion");
		this.codeLabel.UseMarkup = true;
		this.frame1.LabelWidget = this.codeLabel;
		this.vbox2.Add (this.frame1);
		global::Gtk.Box.BoxChild w17 = ((global::Gtk.Box.BoxChild)(this.vbox2 [this.frame1]));
		w17.Position = 0;
		w17.Expand = false;
		w17.Fill = false;
		// Container child vbox2.Gtk.Box+BoxChild
		this.frame5 = new global::Gtk.Frame ();
		this.frame5.Name = "frame5";
		this.frame5.ShadowType = ((global::Gtk.ShadowType)(0));
		// Container child frame5.Gtk.Container+ContainerChild
		this.GtkAlignment5 = new global::Gtk.Alignment (0F, 0F, 1F, 1F);
		this.GtkAlignment5.Name = "GtkAlignment5";
		this.GtkAlignment5.LeftPadding = ((uint)(12));
		// Container child GtkAlignment5.Gtk.Container+ContainerChild
		this.psLocation = new global::MASGAU.Gtk.WrapperFileChooserButton ();
		this.psLocation.Events = ((global::Gdk.EventMask)(256));
		this.psLocation.Name = "psLocation";
		this.GtkAlignment5.Add (this.psLocation);
		this.frame5.Add (this.GtkAlignment5);
		this.psLocationLabel = new global::Gtk.Label ();
		this.psLocationLabel.Name = "psLocationLabel";
		this.psLocationLabel.LabelProp = global::Mono.Unix.Catalog.GetString ("PlayStationLocationQuestion");
		this.psLocationLabel.UseMarkup = true;
		this.frame5.LabelWidget = this.psLocationLabel;
		this.vbox2.Add (this.frame5);
		global::Gtk.Box.BoxChild w20 = ((global::Gtk.Box.BoxChild)(this.vbox2 [this.frame5]));
		w20.Position = 1;
		w20.Expand = false;
		w20.Fill = false;
		// Container child vbox2.Gtk.Box+BoxChild
		this.psScanBtn = new global::MASGAU.Gtk.WrappedButton ();
		this.psScanBtn.Events = ((global::Gdk.EventMask)(256));
		this.psScanBtn.Name = "psScanBtn";
		this.psScanBtn.Label = "PlayStationScanButton";
		this.vbox2.Add (this.psScanBtn);
		global::Gtk.Box.BoxChild w21 = ((global::Gtk.Box.BoxChild)(this.vbox2 [this.psScanBtn]));
		w21.Position = 2;
		w21.Expand = false;
		w21.Fill = false;
		this.notebook1.Add (this.vbox2);
		global::Gtk.Notebook.NotebookChild w22 = ((global::Gtk.Notebook.NotebookChild)(this.notebook1 [this.vbox2]));
		w22.Position = 1;
		// Notebook tab
		this.psLabel = new global::Gtk.Label ();
		this.psLabel.Name = "psLabel";
		this.psLabel.LabelProp = global::Mono.Unix.Catalog.GetString ("PlayStation");
		this.notebook1.SetTabLabel (this.vbox2, this.psLabel);
		this.psLabel.ShowAll ();
		// Container child notebook1.Gtk.Notebook+NotebookChild
		this.vbox6 = new global::Gtk.VBox ();
		this.vbox6.Name = "vbox6";
		this.vbox6.Spacing = 6;
		// Container child vbox6.Gtk.Box+BoxChild
		this.frame6 = new global::Gtk.Frame ();
		this.frame6.Name = "frame6";
		this.frame6.ShadowType = ((global::Gtk.ShadowType)(0));
		// Container child frame6.Gtk.Container+ContainerChild
		this.GtkAlignment7 = new global::Gtk.Alignment (0F, 0F, 1F, 1F);
		this.GtkAlignment7.Name = "GtkAlignment7";
		this.GtkAlignment7.LeftPadding = ((uint)(12));
		// Container child GtkAlignment7.Gtk.Container+ContainerChild
		this.emailEntry = new global::MASGAU.Gtk.WrappedEntry ();
		this.emailEntry.Events = ((global::Gdk.EventMask)(256));
		this.emailEntry.Name = "emailEntry";
		this.GtkAlignment7.Add (this.emailEntry);
		this.frame6.Add (this.GtkAlignment7);
		this.emailLabel = new global::Gtk.Label ();
		this.emailLabel.Name = "emailLabel";
		this.emailLabel.LabelProp = global::Mono.Unix.Catalog.GetString ("EmailAddress");
		this.emailLabel.UseMarkup = true;
		this.frame6.LabelWidget = this.emailLabel;
		this.vbox6.Add (this.frame6);
		global::Gtk.Box.BoxChild w25 = ((global::Gtk.Box.BoxChild)(this.vbox6 [this.frame6]));
		w25.Position = 0;
		w25.Expand = false;
		w25.Fill = false;
		this.notebook1.Add (this.vbox6);
		global::Gtk.Notebook.NotebookChild w26 = ((global::Gtk.Notebook.NotebookChild)(this.notebook1 [this.vbox6]));
		w26.Position = 2;
		// Notebook tab
		this.settingsLabel = new global::Gtk.Label ();
		this.settingsLabel.Name = "settingsLabel";
		this.settingsLabel.LabelProp = global::Mono.Unix.Catalog.GetString ("Settings");
		this.notebook1.SetTabLabel (this.vbox6, this.settingsLabel);
		this.settingsLabel.ShowAll ();
		this.vbox1.Add (this.notebook1);
		global::Gtk.Box.BoxChild w27 = ((global::Gtk.Box.BoxChild)(this.vbox1 [this.notebook1]));
		w27.Position = 1;
		this.Add (this.vbox1);
		if ((this.Child != null)) {
			this.Child.ShowAll ();
		}
		this.DefaultWidth = 645;
		this.DefaultHeight = 315;
		this.Show ();
	}
}
