
// This file has been generated by the GUI designer. Do not modify.
namespace MASGAU.Analyzer
{
	public partial class ReportDialog
	{
		private global::Gtk.ScrolledWindow GtkScrolledWindow;
		private global::Gtk.TextView reportText;
		private global::Gtk.Label disclaimerLabel;
		private global::Gtk.Button saveButton;
		private global::Gtk.Button uploadButton;
		private global::Gtk.Button closebutton;
		
		protected virtual void Build ()
		{
			global::Stetic.Gui.Initialize (this);
			// Widget MASGAU.Analyzer.ReportDialog
			this.Name = "MASGAU.Analyzer.ReportDialog";
			this.Title = global::Mono.Unix.Catalog.GetString ("ReportWindowTitle");
			this.WindowPosition = ((global::Gtk.WindowPosition)(4));
			this.DefaultWidth = 600;
			this.DefaultHeight = 400;
			// Internal child MASGAU.Analyzer.ReportDialog.VBox
			global::Gtk.VBox w1 = this.VBox;
			w1.Name = "dialog1_VBox";
			w1.BorderWidth = ((uint)(2));
			// Container child dialog1_VBox.Gtk.Box+BoxChild
			this.GtkScrolledWindow = new global::Gtk.ScrolledWindow ();
			this.GtkScrolledWindow.Name = "GtkScrolledWindow";
			this.GtkScrolledWindow.VscrollbarPolicy = ((global::Gtk.PolicyType)(0));
			this.GtkScrolledWindow.HscrollbarPolicy = ((global::Gtk.PolicyType)(0));
			this.GtkScrolledWindow.ShadowType = ((global::Gtk.ShadowType)(1));
			// Container child GtkScrolledWindow.Gtk.Container+ContainerChild
			this.reportText = new global::Gtk.TextView ();
			this.reportText.CanFocus = true;
			this.reportText.Name = "reportText";
			this.GtkScrolledWindow.Add (this.reportText);
			w1.Add (this.GtkScrolledWindow);
			global::Gtk.Box.BoxChild w3 = ((global::Gtk.Box.BoxChild)(w1 [this.GtkScrolledWindow]));
			w3.Position = 0;
			// Container child dialog1_VBox.Gtk.Box+BoxChild
			this.disclaimerLabel = new global::Gtk.Label ();
			this.disclaimerLabel.Name = "disclaimerLabel";
			this.disclaimerLabel.LabelProp = global::Mono.Unix.Catalog.GetString ("AnalyzerDisclaimer");
			this.disclaimerLabel.Wrap = true;
			w1.Add (this.disclaimerLabel);
			global::Gtk.Box.BoxChild w4 = ((global::Gtk.Box.BoxChild)(w1 [this.disclaimerLabel]));
			w4.Position = 1;
			w4.Expand = false;
			w4.Fill = false;
			// Internal child MASGAU.Analyzer.ReportDialog.ActionArea
			global::Gtk.HButtonBox w5 = this.ActionArea;
			w5.Name = "dialog1_ActionArea";
			w5.Spacing = 10;
			w5.BorderWidth = ((uint)(5));
			w5.LayoutStyle = ((global::Gtk.ButtonBoxStyle)(4));
			// Container child dialog1_ActionArea.Gtk.ButtonBox+ButtonBoxChild
			this.saveButton = new global::Gtk.Button ();
			this.saveButton.CanDefault = true;
			this.saveButton.CanFocus = true;
			this.saveButton.Name = "saveButton";
			this.saveButton.UseUnderline = true;
			// Container child saveButton.Gtk.Container+ContainerChild
			global::Gtk.Alignment w6 = new global::Gtk.Alignment (0.5F, 0.5F, 0F, 0F);
			// Container child GtkAlignment.Gtk.Container+ContainerChild
			global::Gtk.HBox w7 = new global::Gtk.HBox ();
			w7.Spacing = 2;
			// Container child GtkHBox.Gtk.Container+ContainerChild
			global::Gtk.Image w8 = new global::Gtk.Image ();
			w8.Pixbuf = global::Stetic.IconLoader.LoadIcon (this, "gtk-save", global::Gtk.IconSize.Menu);
			w7.Add (w8);
			// Container child GtkHBox.Gtk.Container+ContainerChild
			global::Gtk.Label w10 = new global::Gtk.Label ();
			w10.LabelProp = global::Mono.Unix.Catalog.GetString ("SaveButton");
			w10.UseUnderline = true;
			w7.Add (w10);
			w6.Add (w7);
			this.saveButton.Add (w6);
			w5.Add (this.saveButton);
			global::Gtk.ButtonBox.ButtonBoxChild w14 = ((global::Gtk.ButtonBox.ButtonBoxChild)(w5 [this.saveButton]));
			w14.Expand = false;
			w14.Fill = false;
			// Container child dialog1_ActionArea.Gtk.ButtonBox+ButtonBoxChild
			this.uploadButton = new global::Gtk.Button ();
			this.uploadButton.Sensitive = false;
			this.uploadButton.CanDefault = true;
			this.uploadButton.CanFocus = true;
			this.uploadButton.Name = "uploadButton";
			this.uploadButton.UseUnderline = true;
			// Container child uploadButton.Gtk.Container+ContainerChild
			global::Gtk.Alignment w15 = new global::Gtk.Alignment (0.5F, 0.5F, 0F, 0F);
			// Container child GtkAlignment.Gtk.Container+ContainerChild
			global::Gtk.HBox w16 = new global::Gtk.HBox ();
			w16.Spacing = 2;
			// Container child GtkHBox.Gtk.Container+ContainerChild
			global::Gtk.Image w17 = new global::Gtk.Image ();
			w17.Pixbuf = global::Stetic.IconLoader.LoadIcon (this, "gtk-go-up", global::Gtk.IconSize.Menu);
			w16.Add (w17);
			// Container child GtkHBox.Gtk.Container+ContainerChild
			global::Gtk.Label w19 = new global::Gtk.Label ();
			w19.LabelProp = global::Mono.Unix.Catalog.GetString ("UploadButton");
			w19.UseUnderline = true;
			w16.Add (w19);
			w15.Add (w16);
			this.uploadButton.Add (w15);
			w5.Add (this.uploadButton);
			global::Gtk.ButtonBox.ButtonBoxChild w23 = ((global::Gtk.ButtonBox.ButtonBoxChild)(w5 [this.uploadButton]));
			w23.Position = 1;
			w23.Expand = false;
			w23.Fill = false;
			// Container child dialog1_ActionArea.Gtk.ButtonBox+ButtonBoxChild
			this.closebutton = new global::Gtk.Button ();
			this.closebutton.CanFocus = true;
			this.closebutton.Name = "closebutton";
			this.closebutton.UseUnderline = true;
			// Container child closebutton.Gtk.Container+ContainerChild
			global::Gtk.Alignment w24 = new global::Gtk.Alignment (0.5F, 0.5F, 0F, 0F);
			// Container child GtkAlignment.Gtk.Container+ContainerChild
			global::Gtk.HBox w25 = new global::Gtk.HBox ();
			w25.Spacing = 2;
			// Container child GtkHBox.Gtk.Container+ContainerChild
			global::Gtk.Image w26 = new global::Gtk.Image ();
			w26.Pixbuf = global::Stetic.IconLoader.LoadIcon (this, "gtk-close", global::Gtk.IconSize.Menu);
			w25.Add (w26);
			// Container child GtkHBox.Gtk.Container+ContainerChild
			global::Gtk.Label w28 = new global::Gtk.Label ();
			w28.LabelProp = global::Mono.Unix.Catalog.GetString ("CloseButton");
			w28.UseUnderline = true;
			w25.Add (w28);
			w24.Add (w25);
			this.closebutton.Add (w24);
			this.AddActionWidget (this.closebutton, -7);
			global::Gtk.ButtonBox.ButtonBoxChild w32 = ((global::Gtk.ButtonBox.ButtonBoxChild)(w5 [this.closebutton]));
			w32.Position = 2;
			w32.Expand = false;
			w32.Fill = false;
			if ((this.Child != null)) {
				this.Child.ShowAll ();
			}
			this.Show ();
			this.saveButton.Clicked += new global::System.EventHandler (this.OnSaveButtonClicked);
			this.uploadButton.Clicked += new global::System.EventHandler (this.OnUploadButtonClicked);
		}
	}
}
