
// This file has been generated by the GUI designer. Do not modify.
namespace MASGAU.Analyzer
{
	public partial class SearchingDialog
	{
		private global::Gtk.ProgressBar progressbar1;
		private global::Gtk.Button cancelButton;
		
		protected virtual void Build ()
		{
			global::Stetic.Gui.Initialize (this);
			// Widget MASGAU.Analyzer.SearchingDialog
			this.Name = "MASGAU.Analyzer.SearchingDialog";
			this.Title = global::Mono.Unix.Catalog.GetString ("SearchingWindowTitle");
			this.WindowPosition = ((global::Gtk.WindowPosition)(4));
			this.Resizable = false;
			this.AllowGrow = false;
			this.DefaultWidth = 500;
			// Internal child MASGAU.Analyzer.SearchingDialog.VBox
			global::Gtk.VBox w1 = this.VBox;
			w1.Name = "dialog1_VBox";
			w1.BorderWidth = ((uint)(2));
			// Container child dialog1_VBox.Gtk.Box+BoxChild
			this.progressbar1 = new global::Gtk.ProgressBar ();
			this.progressbar1.Name = "progressbar1";
			w1.Add (this.progressbar1);
			global::Gtk.Box.BoxChild w2 = ((global::Gtk.Box.BoxChild)(w1 [this.progressbar1]));
			w2.Position = 0;
			w2.Expand = false;
			w2.Fill = false;
			// Internal child MASGAU.Analyzer.SearchingDialog.ActionArea
			global::Gtk.HButtonBox w3 = this.ActionArea;
			w3.Name = "__gtksharp_86_Stetic_TopLevelDialog_ActionArea";
			// Container child __gtksharp_86_Stetic_TopLevelDialog_ActionArea.Gtk.ButtonBox+ButtonBoxChild
			this.cancelButton = new global::Gtk.Button ();
			this.cancelButton.CanFocus = true;
			this.cancelButton.Name = "cancelButton";
			this.cancelButton.UseUnderline = true;
			this.cancelButton.Label = global::Mono.Unix.Catalog.GetString ("CancelButton");
			this.AddActionWidget (this.cancelButton, 0);
			global::Gtk.ButtonBox.ButtonBoxChild w4 = ((global::Gtk.ButtonBox.ButtonBoxChild)(w3 [this.cancelButton]));
			w4.Expand = false;
			w4.Fill = false;
			if ((this.Child != null)) {
				this.Child.ShowAll ();
			}
			this.DefaultHeight = 94;
			this.Show ();
			this.Close += new global::System.EventHandler (this.OnClose);
		}
	}
}
